Disable OMPL's demos in moveit2 image (#228).
This commit disables OMPL's demos, due to a build error that results in a
header file not being found.

```
<PATH_TO_OMPL>/demos/DubinsAirplane.cpp:48:10: fatal error: ompl/tools/debug/Profiler.h: No such file or directory
   48 | #include <ompl/tools/debug/Profiler.h>
```